<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="TcAxisCommand" Id="{f9a234cf-ef1c-447a-9e2d-1effbffa062c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TcAxisCommand IMPLEMENTS itfAxisCommand
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Update" Id="{0d1a4fff-7089-4186-8730-c136d6df7aa7}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Update 		: MC_Error
VAR_INPUT
	Position		: REAL;
	Velocity		: REAL;
	EndVelocity		: REAL;
	Acceleration	: REAL;
	Deceleration	: REAL;
	Jerk			: REAL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>