<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="TcAxis" Id="{368b1f8e-b60b-49ff-9958-1a508f58502d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TcAxis IMPLEMENTS itfAxis
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="AccelerationProfile" Id="{1075a648-7755-4113-b6bf-3e3504274adb}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD AccelerationProfile : itfCommand
VAR_INPUT
	TimeScale	: REAL;
	AccelerationScale	: REAL;
	Offset	: REAL;
	BufferMode	: MC_BUFFER_MODE;
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">10L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Property Name="ActualPosition" Id="{ce0fed92-57ae-49b7-b0c0-f04059b2e610}">
      <Declaration><![CDATA[{warning 'Agregar implementación de propiedad'}
PROPERTY ActualPosition : REAL
]]></Declaration>
      <Get Name="Get" Id="{9f21e0fe-998e-4d3f-b873-b75b261ff14f}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <NWL>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="NWLImplementationObject">
                  <v n="NetworkListComment">""</v>
                  <v n="DefaultViewMode">"Fbd"</v>
                  <l2 n="NetworkList" cet="Network">
                    <o>
                      <v n="ILActive">false</v>
                      <v n="FBDValid">false</v>
                      <v n="ILValid">false</v>
                      <l2 n="ILLines" />
                      <v n="Comment">""</v>
                      <v n="Title">""</v>
                      <v n="Label">""</v>
                      <v n="OutCommented">false</v>
                      <l2 n="NetworkItems" />
                      <l2 n="Connectors" />
                      <v n="Id">2L</v>
                    </o>
                  </l2>
                  <v n="BranchCounter">1</v>
                  <v n="ValidIds">true</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="Int32">System.Int32</Type>
                <Type n="Int64">System.Int64</Type>
                <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
                <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
                <Type n="String">System.String</Type>
              </TypeList>
            </XmlArchive>
          </NWL>
        </Implementation>
      </Get>
    </Property>
    <Property Name="ActualTorque" Id="{02b01523-d219-47cf-bc4c-9934eb2f230d}">
      <Declaration><![CDATA[{warning 'Agregar implementación de propiedad'}
PROPERTY ActualTorque : REAL
]]></Declaration>
      <Get Name="Get" Id="{ee42702a-b0e7-4587-8c19-6988ddf36ff7}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <NWL>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="NWLImplementationObject">
                  <v n="NetworkListComment">""</v>
                  <v n="DefaultViewMode">"Fbd"</v>
                  <l2 n="NetworkList" cet="Network">
                    <o>
                      <v n="ILActive">false</v>
                      <v n="FBDValid">false</v>
                      <v n="ILValid">false</v>
                      <l2 n="ILLines" />
                      <v n="Comment">""</v>
                      <v n="Title">""</v>
                      <v n="Label">""</v>
                      <v n="OutCommented">false</v>
                      <l2 n="NetworkItems" />
                      <l2 n="Connectors" />
                      <v n="Id">2L</v>
                    </o>
                  </l2>
                  <v n="BranchCounter">1</v>
                  <v n="ValidIds">true</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="Int32">System.Int32</Type>
                <Type n="Int64">System.Int64</Type>
                <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
                <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
                <Type n="String">System.String</Type>
              </TypeList>
            </XmlArchive>
          </NWL>
        </Implementation>
      </Get>
    </Property>
    <Property Name="ActualVelocity" Id="{402f4290-e6c5-4255-9578-ea4382d1cbc6}">
      <Declaration><![CDATA[{warning 'Agregar implementación de propiedad'}
PROPERTY ActualVelocity : REAL
]]></Declaration>
      <Get Name="Get" Id="{bd5bde10-b0a1-4a12-8f89-48c6e89be57f}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <NWL>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="NWLImplementationObject">
                  <v n="NetworkListComment">""</v>
                  <v n="DefaultViewMode">"Fbd"</v>
                  <l2 n="NetworkList" cet="Network">
                    <o>
                      <v n="ILActive">false</v>
                      <v n="FBDValid">false</v>
                      <v n="ILValid">false</v>
                      <l2 n="ILLines" />
                      <v n="Comment">""</v>
                      <v n="Title">""</v>
                      <v n="Label">""</v>
                      <v n="OutCommented">false</v>
                      <l2 n="NetworkItems" />
                      <l2 n="Connectors" />
                      <v n="Id">2L</v>
                    </o>
                  </l2>
                  <v n="BranchCounter">1</v>
                  <v n="ValidIds">true</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="Int32">System.Int32</Type>
                <Type n="Int64">System.Int64</Type>
                <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
                <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
                <Type n="String">System.String</Type>
              </TypeList>
            </XmlArchive>
          </NWL>
        </Implementation>
      </Get>
    </Property>
    <Property Name="AxisWarning" Id="{da4299a5-b6a2-490d-88b1-008fc54147b5}">
      <Declaration><![CDATA[{warning 'Agregar implementación de propiedad'}
PROPERTY AxisWarning : BOOL
]]></Declaration>
      <Get Name="Get" Id="{80951fbd-fd77-498c-8d03-4edfe8bbe51d}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <NWL>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="NWLImplementationObject">
                  <v n="NetworkListComment">""</v>
                  <v n="DefaultViewMode">"Fbd"</v>
                  <l2 n="NetworkList" cet="Network">
                    <o>
                      <v n="ILActive">false</v>
                      <v n="FBDValid">false</v>
                      <v n="ILValid">false</v>
                      <l2 n="ILLines" />
                      <v n="Comment">""</v>
                      <v n="Title">""</v>
                      <v n="Label">""</v>
                      <v n="OutCommented">false</v>
                      <l2 n="NetworkItems" />
                      <l2 n="Connectors" />
                      <v n="Id">2L</v>
                    </o>
                  </l2>
                  <v n="BranchCounter">1</v>
                  <v n="ValidIds">true</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="Int32">System.Int32</Type>
                <Type n="Int64">System.Int64</Type>
                <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
                <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
                <Type n="String">System.String</Type>
              </TypeList>
            </XmlArchive>
          </NWL>
        </Implementation>
      </Get>
    </Property>
    <Method Name="CamIn" Id="{472ab343-02d0-481b-ac2a-15d9b38d6eec}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD CamIn : itfSynchronizedAxisCommand
VAR_INPUT
	Master	: itfAxis;
	MasterOffset	: REAL;
	SlaveOffset	: REAL;
	MasterScaling	: REAL;
	SlaveScaling	: REAL;
	MasterStartDistance	: REAL;
	MasterSyncPosition	: REAL;
	StartMode	: MC_StartMode;
	MasterValueSource	: MC_Source;
	CamTable	: itfCamTable;
	BufferMode	: MC_BUFFER_MODE;
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">17L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Method Name="CombineAxes" Id="{9f037da3-2653-4473-a978-0661545fe3f5}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD CombineAxes : itfSynchronizedAxisCommand
VAR_INPUT
	Master1	: itfAxis;
	Master2	: itfAxis;
	CombineMode	: MC_COMBINE_MODE;
	GearRatioNumeratorM1	: INT;
	GearRatioDenominatorM1	: INT;
	GearRatioNumeratorM2	: INT;
	GearRatioDenominatorM2	: INT;
	MasterValueSourceM1	: MC_SOURCE;
	MasterValueSourceM2	: MC_SOURCE;
	BufferMode	: MC_BUFFER_MODE;
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">16L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Property Name="CommunicationReady" Id="{da27e9b4-6526-46f6-977f-67e6291a5827}">
      <Declaration><![CDATA[{warning 'Agregar implementación de propiedad'}
PROPERTY CommunicationReady : BOOL
]]></Declaration>
      <Get Name="Get" Id="{2334b9cc-8d4b-483c-b565-721a2ebffa89}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <NWL>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="NWLImplementationObject">
                  <v n="NetworkListComment">""</v>
                  <v n="DefaultViewMode">"Fbd"</v>
                  <l2 n="NetworkList" cet="Network">
                    <o>
                      <v n="ILActive">false</v>
                      <v n="FBDValid">false</v>
                      <v n="ILValid">false</v>
                      <l2 n="ILLines" />
                      <v n="Comment">""</v>
                      <v n="Title">""</v>
                      <v n="Label">""</v>
                      <v n="OutCommented">false</v>
                      <l2 n="NetworkItems" />
                      <l2 n="Connectors" />
                      <v n="Id">2L</v>
                    </o>
                  </l2>
                  <v n="BranchCounter">1</v>
                  <v n="ValidIds">true</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="Int32">System.Int32</Type>
                <Type n="Int64">System.Int64</Type>
                <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
                <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
                <Type n="String">System.String</Type>
              </TypeList>
            </XmlArchive>
          </NWL>
        </Implementation>
      </Get>
    </Property>
    <Property Name="Direction" Id="{dd9ce4ae-907d-4f51-a21b-37f23f264f65}">
      <Declaration><![CDATA[{warning 'Agregar implementación de propiedad'}
PROPERTY Direction : AXIS_DIRECTION
]]></Declaration>
      <Get Name="Get" Id="{83a7a733-ad34-4382-9c0f-2ffbad9241cf}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <NWL>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="NWLImplementationObject">
                  <v n="NetworkListComment">""</v>
                  <v n="DefaultViewMode">"Fbd"</v>
                  <l2 n="NetworkList" cet="Network">
                    <o>
                      <v n="ILActive">false</v>
                      <v n="FBDValid">false</v>
                      <v n="ILValid">false</v>
                      <l2 n="ILLines" />
                      <v n="Comment">""</v>
                      <v n="Title">""</v>
                      <v n="Label">""</v>
                      <v n="OutCommented">false</v>
                      <l2 n="NetworkItems" />
                      <l2 n="Connectors" />
                      <v n="Id">2L</v>
                    </o>
                  </l2>
                  <v n="BranchCounter">1</v>
                  <v n="ValidIds">true</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="Int32">System.Int32</Type>
                <Type n="Int64">System.Int64</Type>
                <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
                <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
                <Type n="String">System.String</Type>
              </TypeList>
            </XmlArchive>
          </NWL>
        </Implementation>
      </Get>
    </Property>
    <Property Name="ErrorId" Id="{e9440a7a-9635-4160-8451-93090ac81a3f}">
      <Declaration><![CDATA[{warning 'Agregar implementación de propiedad'}
PROPERTY ErrorId : WORD
]]></Declaration>
      <Get Name="Get" Id="{2e70d1ef-d80f-422d-8ada-ca9ca8194d3c}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <NWL>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="NWLImplementationObject">
                  <v n="NetworkListComment">""</v>
                  <v n="DefaultViewMode">"Fbd"</v>
                  <l2 n="NetworkList" cet="Network">
                    <o>
                      <v n="ILActive">false</v>
                      <v n="FBDValid">false</v>
                      <v n="ILValid">false</v>
                      <l2 n="ILLines" />
                      <v n="Comment">""</v>
                      <v n="Title">""</v>
                      <v n="Label">""</v>
                      <v n="OutCommented">false</v>
                      <l2 n="NetworkItems" />
                      <l2 n="Connectors" />
                      <v n="Id">2L</v>
                    </o>
                  </l2>
                  <v n="BranchCounter">1</v>
                  <v n="ValidIds">true</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="Int32">System.Int32</Type>
                <Type n="Int64">System.Int64</Type>
                <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
                <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
                <Type n="String">System.String</Type>
              </TypeList>
            </XmlArchive>
          </NWL>
        </Implementation>
      </Get>
    </Property>
    <Method Name="GearIn" Id="{ea0d2e85-4cfa-4f9a-8efc-c2ec28fb18fc}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD GearIn : itfSynchronizedAxisCommand
VAR_INPUT
	Master	: itfAxis;
	Ratio	: REAL;
	MasterValueSource	: INT;
	Acceleration	: REAL;
	Deceleration	: REAL;
	Jerk	: REAL;
	BufferMode	: MC_BUFFER_MODE;
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">13L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Method Name="GearInPos" Id="{1b6dbd41-167b-4f03-ba62-cd270e9170cf}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD GearInPos : itfSynchronizedAxisCommand
VAR_INPUT
	Master	: itfAxis;
	RatioNumerator	: REAL;
	RatioDenominator	: REAL;
	MasterValueSource	: MC_SOURCE;
	MasterSyncPosition	: REAL;
	SlaveSyncPosition	: REAL;
	SyncMode	: MC_SYNC_MODE;
	MasterStartDistance	: REAL;
	Velocity	: REAL;
	Acceleration	: REAL;
	Deceleration	: REAL;
	Jerk	: REAL;
	BufferMode	: MC_BUFFER_MODE;
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">19L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Method Name="Halt" Id="{12747595-f732-41d8-9b7e-71fb31478a24}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD Halt : itfAxisCommand
VAR_INPUT
	Deceleration	: REAL;
	Jerk	: REAL;
	BufferMode	: MC_BUFFER_MODE;
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">9L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Method Name="HaltSuperimposed" Id="{9860ab4f-9fcd-4c01-84b1-90602398ef34}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD HaltSuperimposed : itfAxisCommand
VAR_INPUT
	Deceleration	: REAL;
	Jerk	: REAL;
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">8L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Method Name="Home" Id="{0376ca23-c965-40d7-93d6-09dd349abfd6}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD Home : itfAxisCommand
VAR_INPUT
	Position		: REAL;
	Velocity		: REAL;
	EndVelocity		: REAL;
	Acceleration	: REAL;
	Deceleration	: REAL;
	Jerk			: REAL;
	Direction		: MC_Direction;
	HomingMode		: INT;
	BufferMode		: MC_BUFFER_MODE;
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">15L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Property Name="HomeAbsSwitch" Id="{e8373e7d-1ba9-4395-8a6d-ca03d0743b1d}">
      <Declaration><![CDATA[{warning 'Agregar implementación de propiedad'}
PROPERTY HomeAbsSwitch : BOOL
]]></Declaration>
      <Get Name="Get" Id="{becf46c9-0584-4de5-88b5-f2872b2b082a}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <NWL>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="NWLImplementationObject">
                  <v n="NetworkListComment">""</v>
                  <v n="DefaultViewMode">"Fbd"</v>
                  <l2 n="NetworkList" cet="Network">
                    <o>
                      <v n="ILActive">false</v>
                      <v n="FBDValid">false</v>
                      <v n="ILValid">false</v>
                      <l2 n="ILLines" />
                      <v n="Comment">""</v>
                      <v n="Title">""</v>
                      <v n="Label">""</v>
                      <v n="OutCommented">false</v>
                      <l2 n="NetworkItems" />
                      <l2 n="Connectors" />
                      <v n="Id">2L</v>
                    </o>
                  </l2>
                  <v n="BranchCounter">1</v>
                  <v n="ValidIds">true</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="Int32">System.Int32</Type>
                <Type n="Int64">System.Int64</Type>
                <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
                <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
                <Type n="String">System.String</Type>
              </TypeList>
            </XmlArchive>
          </NWL>
        </Implementation>
      </Get>
    </Property>
    <Property Name="IsHomed" Id="{8c2bc4e7-c608-466a-935b-3fc2dcb93e13}">
      <Declaration><![CDATA[{warning 'Agregar implementación de propiedad'}
PROPERTY IsHomed : BOOL
]]></Declaration>
      <Get Name="Get" Id="{0b6abe29-58ad-4879-afea-7f6fc1927dd8}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <NWL>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="NWLImplementationObject">
                  <v n="NetworkListComment">""</v>
                  <v n="DefaultViewMode">"Fbd"</v>
                  <l2 n="NetworkList" cet="Network">
                    <o>
                      <v n="ILActive">false</v>
                      <v n="FBDValid">false</v>
                      <v n="ILValid">false</v>
                      <l2 n="ILLines" />
                      <v n="Comment">""</v>
                      <v n="Title">""</v>
                      <v n="Label">""</v>
                      <v n="OutCommented">false</v>
                      <l2 n="NetworkItems" />
                      <l2 n="Connectors" />
                      <v n="Id">2L</v>
                    </o>
                  </l2>
                  <v n="BranchCounter">1</v>
                  <v n="ValidIds">true</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="Int32">System.Int32</Type>
                <Type n="Int64">System.Int64</Type>
                <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
                <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
                <Type n="String">System.String</Type>
              </TypeList>
            </XmlArchive>
          </NWL>
        </Implementation>
      </Get>
    </Property>
    <Property Name="LimitSwitchNegative" Id="{88856312-390b-4563-81db-2f23054ba39d}">
      <Declaration><![CDATA[{warning 'Agregar implementación de propiedad'}
PROPERTY LimitSwitchNegative : BOOL
]]></Declaration>
      <Get Name="Get" Id="{0a2a49d4-b8f4-4b77-aae7-6e8564991793}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <NWL>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="NWLImplementationObject">
                  <v n="NetworkListComment">""</v>
                  <v n="DefaultViewMode">"Fbd"</v>
                  <l2 n="NetworkList" cet="Network">
                    <o>
                      <v n="ILActive">false</v>
                      <v n="FBDValid">false</v>
                      <v n="ILValid">false</v>
                      <l2 n="ILLines" />
                      <v n="Comment">""</v>
                      <v n="Title">""</v>
                      <v n="Label">""</v>
                      <v n="OutCommented">false</v>
                      <l2 n="NetworkItems" />
                      <l2 n="Connectors" />
                      <v n="Id">2L</v>
                    </o>
                  </l2>
                  <v n="BranchCounter">1</v>
                  <v n="ValidIds">true</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="Int32">System.Int32</Type>
                <Type n="Int64">System.Int64</Type>
                <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
                <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
                <Type n="String">System.String</Type>
              </TypeList>
            </XmlArchive>
          </NWL>
        </Implementation>
      </Get>
    </Property>
    <Property Name="LimitSwitchPositive" Id="{8699f8d7-b138-4c48-9550-4247448db606}">
      <Declaration><![CDATA[{warning 'Agregar implementación de propiedad'}
PROPERTY LimitSwitchPositive : BOOL
]]></Declaration>
      <Get Name="Get" Id="{9a1fb03d-d089-4f9f-b50f-0115f4c3c5ba}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <NWL>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="NWLImplementationObject">
                  <v n="NetworkListComment">""</v>
                  <v n="DefaultViewMode">"Fbd"</v>
                  <l2 n="NetworkList" cet="Network">
                    <o>
                      <v n="ILActive">false</v>
                      <v n="FBDValid">false</v>
                      <v n="ILValid">false</v>
                      <l2 n="ILLines" />
                      <v n="Comment">""</v>
                      <v n="Title">""</v>
                      <v n="Label">""</v>
                      <v n="OutCommented">false</v>
                      <l2 n="NetworkItems" />
                      <l2 n="Connectors" />
                      <v n="Id">2L</v>
                    </o>
                  </l2>
                  <v n="BranchCounter">1</v>
                  <v n="ValidIds">true</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="Int32">System.Int32</Type>
                <Type n="Int64">System.Int64</Type>
                <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
                <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
                <Type n="String">System.String</Type>
              </TypeList>
            </XmlArchive>
          </NWL>
        </Implementation>
      </Get>
    </Property>
    <Property Name="MotionStatus" Id="{2ca02dbc-84af-487b-9a5a-fafc0142a94d}">
      <Declaration><![CDATA[{warning 'Agregar implementación de propiedad'}
PROPERTY MotionStatus : MOTION_STATUS
]]></Declaration>
      <Get Name="Get" Id="{c738715a-98b8-40c2-9ee6-121034c68aa0}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <NWL>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="NWLImplementationObject">
                  <v n="NetworkListComment">""</v>
                  <v n="DefaultViewMode">"Fbd"</v>
                  <l2 n="NetworkList" cet="Network">
                    <o>
                      <v n="ILActive">false</v>
                      <v n="FBDValid">false</v>
                      <v n="ILValid">false</v>
                      <l2 n="ILLines" />
                      <v n="Comment">""</v>
                      <v n="Title">""</v>
                      <v n="Label">""</v>
                      <v n="OutCommented">false</v>
                      <l2 n="NetworkItems" />
                      <l2 n="Connectors" />
                      <v n="Id">2L</v>
                    </o>
                  </l2>
                  <v n="BranchCounter">1</v>
                  <v n="ValidIds">true</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="Int32">System.Int32</Type>
                <Type n="Int64">System.Int64</Type>
                <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
                <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
                <Type n="String">System.String</Type>
              </TypeList>
            </XmlArchive>
          </NWL>
        </Implementation>
      </Get>
    </Property>
    <Method Name="MoveAbsolute" Id="{b338026a-991e-4647-a236-dceb97aaca96}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD MoveAbsolute : itfAxisCommand
VAR_INPUT
	Position		: REAL;
	Velocity		: REAL;
	Acceleration	: REAL;
	Deceleration	: REAL;
	Jerk			: REAL;
	Direction		: MC_Direction;
	BufferMode		: MC_BUFFER_MODE;
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">13L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Method Name="MoveAdditive" Id="{46ab2211-c3ee-4736-a82f-d0c9d4d5dad6}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD MoveAdditive : itfAxisCommand
VAR_INPUT
	Distance	: REAL;
	Velocity	: REAL;
	Acceleration	: REAL;
	Deceleration	: REAL;
	Jerk	: REAL;
	BufferMode	: MC_BUFFER_MODE;
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">12L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Method Name="MoveContinuousAbsolute" Id="{bed1abe5-a176-4351-ad2d-9fb76e1ef691}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD MoveContinuousAbsolute : itfContinuousAxisCommand
VAR_INPUT
	Position		: REAL;
	EndVelocity		: REAL;
	Velocity		: REAL;
	Acceleration	: REAL;
	Deceleration	: REAL;
	Jerk			: REAL;
	Direction		: MC_Direction;
	BufferMode		: MC_BUFFER_MODE;
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">14L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Method Name="MoveContinuousRelative" Id="{b31debd8-72ce-4d76-b8b7-cef8d4634d9c}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD MoveContinuousRelative : itfContinuousAxisCommand
VAR_INPUT
	Distance		: REAL;
	EndVelocity		: REAL;
	Velocity		: REAL;
	Acceleration	: REAL;
	Deceleration	: REAL;
	Jerk			: REAL;
	Direction		: MC_Direction;
	BufferMode		: MC_BUFFER_MODE;
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">14L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Method Name="MoveRelative" Id="{393ddb4a-581e-4bda-920b-a79e52135279}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD MoveRelative : itfAxisCommand
VAR_INPUT
	Distance	: REAL;
	Velocity	: REAL;
	Acceleration	: REAL;
	Deceleration	: REAL;
	Jerk	: REAL;
	BufferMode	: MC_BUFFER_MODE;
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">12L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Method Name="MoveSuperimposed" Id="{3f92cab8-0fe9-4dd4-bd65-cab3375c5be5}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD MoveSuperimposed : itfAxisCommand
VAR_INPUT
	Distance	: REAL;
	VelocityDiff	: REAL;
	Acceleration	: REAL;
	Deceleration	: REAL;
	Jerk	: REAL;
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">11L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Method Name="MoveVelocity" Id="{307b84ee-e086-4573-a720-8dc5a965a7a6}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD MoveVelocity : itfContinuousAxisCommand
VAR_INPUT
	Velocity		: REAL;
	Acceleration	: REAL;
	Deceleration	: REAL;
	Jerk			: REAL;
	Direction		: MC_Direction;
	BufferMode		: MC_BUFFER_MODE;
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">12L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Method Name="PhasingAbsolute" Id="{c2f1be21-8969-4162-9fdd-b5d41c0a22a4}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD PhasingAbsolute : itfSynchronizedAxisCommand
VAR_INPUT
	Master	: itfAxis;
	PhaseShift	: REAL;
	Velocity	: REAL;
	Acceleration	: REAL;
	Deceleration	: REAL;
	Jerk	: REAL;
	BufferMode	: MC_BUFFER_MODE;
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">13L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Method Name="PhasingRelative" Id="{13551c43-e973-434d-ab46-1742e296072e}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD PhasingRelative : itfSynchronizedAxisCommand
VAR_INPUT
	Master	: itfAxis;
	PhaseShift	: REAL;
	Velocity	: REAL;
	Acceleration	: REAL;
	Deceleration	: REAL;
	Jerk	: REAL;
	BufferMode	: MC_BUFFER_MODE;
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">13L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Method Name="PositionProfile" Id="{52d05a1e-414b-40fa-96f3-0139ddd8b994}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD PositionProfile : itfCommand
VAR_INPUT
	TimeScale	: REAL;
	PositionScale	: REAL;
	Offset	: REAL;
	BufferMode	: MC_BUFFER_MODE;
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">10L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Method Name="Power" Id="{c6b267ca-82ec-44ed-8ab2-a85b6b3ddf1d}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD Power : itfCommand
VAR_INPUT
	Enable	: BOOL;
	EnablePositive	: BOOL;
	EnableNegative	: BOOL;
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">9L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Property Name="PowerOn" Id="{8681021f-1573-406d-a50f-7068604356bf}">
      <Declaration><![CDATA[{warning 'Agregar implementación de propiedad'}
PROPERTY PowerOn : BOOL
]]></Declaration>
      <Get Name="Get" Id="{36bbda8f-c384-44fe-bb1b-60a7fef4345e}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <NWL>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="NWLImplementationObject">
                  <v n="NetworkListComment">""</v>
                  <v n="DefaultViewMode">"Fbd"</v>
                  <l2 n="NetworkList" cet="Network">
                    <o>
                      <v n="ILActive">false</v>
                      <v n="FBDValid">false</v>
                      <v n="ILValid">false</v>
                      <l2 n="ILLines" />
                      <v n="Comment">""</v>
                      <v n="Title">""</v>
                      <v n="Label">""</v>
                      <v n="OutCommented">false</v>
                      <l2 n="NetworkItems" />
                      <l2 n="Connectors" />
                      <v n="Id">2L</v>
                    </o>
                  </l2>
                  <v n="BranchCounter">1</v>
                  <v n="ValidIds">true</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="Int32">System.Int32</Type>
                <Type n="Int64">System.Int64</Type>
                <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
                <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
                <Type n="String">System.String</Type>
              </TypeList>
            </XmlArchive>
          </NWL>
        </Implementation>
      </Get>
    </Property>
    <Method Name="ReadBoolParameter" Id="{b68475aa-e949-49a3-9447-28a7658d9155}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD ReadBoolParameter : MC_Error
VAR_INPUT
	ParameterNumber	: INT;
END_VAR
VAR_OUTPUT
	Value	: BOOL;
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">10L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Method Name="ReadParameter" Id="{b73bc47c-ef5e-4a54-9f6d-d3837e768c39}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD ReadParameter : MC_Error
VAR_INPUT
	ParameterNumber	: INT;
END_VAR
VAR_OUTPUT
	Value	: REAL;
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">10L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Property Name="ReadyForPowerOn" Id="{ab8d7588-adc3-4096-b56b-8fe10f2a3b31}">
      <Declaration><![CDATA[{warning 'Agregar implementación de propiedad'}
PROPERTY ReadyForPowerOn : BOOL
]]></Declaration>
      <Get Name="Get" Id="{724c946f-7fd4-42a0-a365-aff206e372f9}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <NWL>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="NWLImplementationObject">
                  <v n="NetworkListComment">""</v>
                  <v n="DefaultViewMode">"Fbd"</v>
                  <l2 n="NetworkList" cet="Network">
                    <o>
                      <v n="ILActive">false</v>
                      <v n="FBDValid">false</v>
                      <v n="ILValid">false</v>
                      <l2 n="ILLines" />
                      <v n="Comment">""</v>
                      <v n="Title">""</v>
                      <v n="Label">""</v>
                      <v n="OutCommented">false</v>
                      <l2 n="NetworkItems" />
                      <l2 n="Connectors" />
                      <v n="Id">2L</v>
                    </o>
                  </l2>
                  <v n="BranchCounter">1</v>
                  <v n="ValidIds">true</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="Int32">System.Int32</Type>
                <Type n="Int64">System.Int64</Type>
                <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
                <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
                <Type n="String">System.String</Type>
              </TypeList>
            </XmlArchive>
          </NWL>
        </Implementation>
      </Get>
    </Property>
    <Method Name="Release" Id="{29138b56-167b-4c70-b8f6-aa30645fff2f}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD Release : MC_Error
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">4L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Method Name="Reset" Id="{e8999349-aede-4f87-82ce-85afadb1c517}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD Reset : itfCommand
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">4L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Method Name="SetOverride" Id="{5bcdf8f3-985f-4f43-9ac3-18b393299b48}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD SetOverride : MC_Error
VAR_INPUT
	VelFactor	: REAL;
	AccFactor	: REAL;
	JerkFactor	: REAL;
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">9L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Method Name="SetPosition" Id="{53a448e3-a276-42e5-b449-1c87a2255125}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD SetPosition : itfCommand
VAR_INPUT
	Position	: REAL;
	Relative	: BOOL;
	ExecutionMode	: MC_ExecutionMode;
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">9L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Property Name="Simulation" Id="{f7329b7b-4312-4b80-878b-aa3d879eb927}">
      <Declaration><![CDATA[{warning 'Agregar implementación de propiedad'}
PROPERTY Simulation : BOOL
]]></Declaration>
      <Get Name="Get" Id="{80c043ae-2feb-4c97-b388-eb8dac9a9e10}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <NWL>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="NWLImplementationObject">
                  <v n="NetworkListComment">""</v>
                  <v n="DefaultViewMode">"Fbd"</v>
                  <l2 n="NetworkList" cet="Network">
                    <o>
                      <v n="ILActive">false</v>
                      <v n="FBDValid">false</v>
                      <v n="ILValid">false</v>
                      <l2 n="ILLines" />
                      <v n="Comment">""</v>
                      <v n="Title">""</v>
                      <v n="Label">""</v>
                      <v n="OutCommented">false</v>
                      <l2 n="NetworkItems" />
                      <l2 n="Connectors" />
                      <v n="Id">2L</v>
                    </o>
                  </l2>
                  <v n="BranchCounter">1</v>
                  <v n="ValidIds">true</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="Int32">System.Int32</Type>
                <Type n="Int64">System.Int64</Type>
                <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
                <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
                <Type n="String">System.String</Type>
              </TypeList>
            </XmlArchive>
          </NWL>
        </Implementation>
      </Get>
    </Property>
    <Property Name="Status" Id="{22bde175-1a2f-4158-bf48-8a70bd3472ec}">
      <Declaration><![CDATA[{warning 'Agregar implementación de propiedad'}
PROPERTY Status : AXIS_STATUS
]]></Declaration>
      <Get Name="Get" Id="{b2660c03-9653-442f-bf06-c04bc6041396}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <NWL>
            <XmlArchive>
              <Data>
                <o xml:space="preserve" t="NWLImplementationObject">
                  <v n="NetworkListComment">""</v>
                  <v n="DefaultViewMode">"Fbd"</v>
                  <l2 n="NetworkList" cet="Network">
                    <o>
                      <v n="ILActive">false</v>
                      <v n="FBDValid">false</v>
                      <v n="ILValid">false</v>
                      <l2 n="ILLines" />
                      <v n="Comment">""</v>
                      <v n="Title">""</v>
                      <v n="Label">""</v>
                      <v n="OutCommented">false</v>
                      <l2 n="NetworkItems" />
                      <l2 n="Connectors" />
                      <v n="Id">2L</v>
                    </o>
                  </l2>
                  <v n="BranchCounter">1</v>
                  <v n="ValidIds">true</v>
                </o>
              </Data>
              <TypeList>
                <Type n="Boolean">System.Boolean</Type>
                <Type n="Int32">System.Int32</Type>
                <Type n="Int64">System.Int64</Type>
                <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
                <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
                <Type n="String">System.String</Type>
              </TypeList>
            </XmlArchive>
          </NWL>
        </Implementation>
      </Get>
    </Property>
    <Method Name="Stop" Id="{8ed85e56-13f3-4629-902d-73916a10f1cf}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD Stop : itfAxisCommand
VAR_INPUT
	Deceleration	: REAL;
	Jerk	: REAL;
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">8L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Method Name="TorqueControl" Id="{e9e31e78-78b2-4758-ac1d-2217067c92b7}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD TorqueControl : itfAxisCommand
VAR_INPUT
	Torque			: REAL;
	TorqueRamp		: REAL;
	Velocity		: REAL;
	Acceleration	: REAL;
	Deceleration	: REAL;
	Jerk			: REAL;
	Direction		: MC_Direction;
	BufferMode		: MC_BUFFER_MODE;
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">14L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Method Name="VelocityProfile" Id="{e23ebeff-1eac-4920-bbf7-238a553fe56d}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD VelocityProfile : itfCommand
VAR_INPUT
	TimeScale	: REAL;
	VelocityScale	: REAL;
	Offset	: REAL;
	BufferMode	: MC_BUFFER_MODE;
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">10L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Method Name="WriteBoolParameter" Id="{0dd59296-4339-4c6f-bb63-4b196789c070}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD WriteBoolParameter : MC_Error
VAR_INPUT
	ParameterNumber	: INT;
	Value	: BOOL;
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">8L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
    <Method Name="WriteParameter" Id="{706416e1-6622-450b-bc64-a6fbc652e913}">
      <Declaration><![CDATA[{warning 'Agregar implementación de método'}
METHOD WriteParameter : MC_Error
VAR_INPUT
	ParameterNumber	: INT;
	Value	: REAL;
END_VAR
]]></Declaration>
      <Implementation>
        <NWL>
          <XmlArchive>
            <Data>
              <o xml:space="preserve" t="NWLImplementationObject">
                <v n="NetworkListComment">""</v>
                <v n="DefaultViewMode">"Fbd"</v>
                <l2 n="NetworkList" cet="Network">
                  <o>
                    <v n="ILActive">false</v>
                    <v n="FBDValid">false</v>
                    <v n="ILValid">false</v>
                    <l2 n="ILLines" />
                    <v n="Comment">""</v>
                    <v n="Title">""</v>
                    <v n="Label">""</v>
                    <v n="OutCommented">false</v>
                    <l2 n="NetworkItems" />
                    <l2 n="Connectors" />
                    <v n="Id">8L</v>
                  </o>
                </l2>
                <v n="BranchCounter">1</v>
                <v n="ValidIds">true</v>
              </o>
            </Data>
            <TypeList>
              <Type n="Boolean">System.Boolean</Type>
              <Type n="Int32">System.Int32</Type>
              <Type n="Int64">System.Int64</Type>
              <Type n="Network">{d9a99d73-b633-47db-b876-a752acb25871}</Type>
              <Type n="NWLImplementationObject">{25e509de-33d4-4447-93f8-c9e4ea381c8b}</Type>
              <Type n="String">System.String</Type>
            </TypeList>
          </XmlArchive>
        </NWL>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>