<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="TcAxis_DMC_Tc3_Direct_Motion_Control" Id="{3ecf364f-113f-4c6b-b875-0e5527cca083}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TcAxis_DMC_Tc3_Direct_Motion_Control IMPLEMENTS itfAxis
VAR_INPUT
	Axis 				: Tc3_Direct_Motion_control.AXIS_REF();
END_VAR
//VAR_OUTPUT
//END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>