<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="TcCommand" Id="{b41e1980-0cf0-4034-bd15-e55e20969f1a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TcCommand IMPLEMENTS itfCommand
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>