<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="TcContinuousAxisCommand" Id="{4161ef74-8cae-4032-9910-f294541a2dec}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TcContinuousAxisCommand IMPLEMENTS itfContinuousAxisCommand
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>