<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="TcCommand" Id="{b41e1980-0cf0-4034-bd15-e55e20969f1a}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TcCommand IMPLEMENTS itfCommand
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Abort" Id="{a0de7d3b-923f-4416-b4ef-58c6f46dbf33}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Abort : MC_Error
VAR
	
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="Active" Id="{fd3da06e-f2a5-45d4-8e0d-ca1c7b52e98a}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY Active : BOOL
]]></Declaration>
      <Get Name="Get" Id="{fc3a9126-fa71-4806-b52e-5be02e326a45}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="Busy" Id="{c70f78a5-d31f-4558-8325-7a017493ec48}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY Busy : BOOL
]]></Declaration>
      <Get Name="Get" Id="{ad9f33f6-5e4a-45f0-9497-56006533bd89}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="Command" Id="{1e98e78f-e26d-4d3f-9df5-62d3db7c2351}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY Command : MC_COMMAND_REF
]]></Declaration>
      <Get Name="Get" Id="{e45bb2ab-5252-4ad9-a904-38438153e8c7}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="CommandAborted" Id="{64fc8e8b-1fca-4237-b95d-a22ade7daee5}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY CommandAborted : BOOL
]]></Declaration>
      <Get Name="Get" Id="{c7567f4a-3327-41fc-9556-98ccbf68eaa5}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="Done" Id="{612a916d-4670-4f93-a6db-9618fe011e35}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY Done : BOOL
]]></Declaration>
      <Get Name="Get" Id="{90c3e97a-8375-42bb-8d60-3a9a9157b587}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="Error" Id="{1a6ee7c5-9948-479d-8097-45d267cf7820}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY Error : BOOL
]]></Declaration>
      <Get Name="Get" Id="{633f7a6f-d36e-45e7-b168-a50576d4d3d1}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="ErrorId" Id="{695df361-2c8d-4b04-9259-0517f9e43c3e}">
      <Declaration><![CDATA[{warning 'add property implementation'}
PROPERTY ErrorId : MC_Error
]]></Declaration>
      <Get Name="Get" Id="{fd1cbed5-a888-4458-8c8c-689361eb11e5}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="Wait" Id="{265638f0-0d66-4716-91e3-9998c65eddaf}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Wait : MC_Error (* This method only makes sense in the IEC 61499 environment*)
VAR_INPUT
	Timeout	: TIME;
	AbortOnTimeout	: BOOL;
END_VAR
VAR
	
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>