<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="TcSynchronizedAxisCommand" Id="{5df8cfc3-abf9-40b2-afe9-4ec11a9d63ce}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TcSynchronizedAxisCommand IMPLEMENTS itfSynchronizedAxisCommand
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>