<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN_Examples" Id="{171499a4-4ffe-4485-87c4-71eaf38382e6}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN_Examples
VAR

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
WareHousingExample();

LabelingExample();

//CamGearExample();


]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>