<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="_MAIN_Examples" Id="{ce97d388-e861-4591-bddd-7771707f573f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM _MAIN_Examples
VAR
//	fbAxis_X1 				: TcAxis_Tc2_MC2;
			
//	fbSum : FB_Sum;
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Examples Tc2_MC2:
WareHousingExample_Tc2_MC2();
//LabelingExample();
//CamGearExample();

//Examples Tc3_DriveMotionControl:
WareHousingExample_Tc3_DriveMotionControl();



]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>