<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_Sum" Id="{d4a8a67c-7d1e-46df-8367-1d72bd208e23}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Sum
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Sum" Id="{c024cfb3-3163-4978-a4cf-a92ae02489d2}">
      <Declaration><![CDATA[{attribute 'TcRpcEnable'}
METHOD Sum : INT
VAR_INPUT
	A : INT;
	B : INT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[Sum := A+B;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>