<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="TcCamTable" Id="{052b4e8b-1a88-4e87-a422-d46dd3c73661}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TcCamTable IMPLEMENTS itfCamTable
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Select" Id="{02640e26-87dd-44e1-9df6-c10a19b174f6}">
      <Declaration><![CDATA[{warning 'add method implementation '}
METHOD Select 		: itfCommand
VAR_INPUT	
	Periodic		: BOOL;
	MasterAbsolute	: BOOL;
	SlaveAbsolute	: BOOL;
	CamTable		: MC_CAM_REF;
END_VAR
VAR
	
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>